### ISSUE TITLE
Question: how use with krakend?

### ISSUE THREAD

**Issue by ihippik** [devopsfaith/bloomfilter#6]
Could you give us an example of using with krakend? I need to filter an array of objects by the value of one of the fields. Is it possible?

**Comment by kpacha** [comment]
hi @ihippik and welcome to the KrakenD community!

a bloomfilter is a structure useful for dealing with huge sets without requiring as much memory space as the traditional set implementations.

The `krakend` package already exposes the required functions to create rejecters used by the JOSE module after verifying the JWT claims.

In order to update the rejecters at each KrakenD node you need to create your custom coordinator and communicate with the nodes using a [`github.com/devopsfaith/bloomfilter/rpc/client.New`](https://godoc.org/github.com/devopsfaith/bloomfilter/rpc/client#New)

cheers
